apiVersion: apps/v1
kind: Deployment
metadata:
  name: task7c
  namespace: sit737
  labels:
    app: sit737_task7c
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: sit737_task7c
  template:
    metadata:
      labels:
        app: sit737_task7c
    spec:
      containers:
      - name: task7p
        image: akshatarora/sit737:task_7c
        ports:
        - containerPort: 3001