apiVersion: v1
kind: Service
metadata:
  name: task7c
  namespace: sit737
spec:
  selector:
    app: sit737_task7c
  ports:
    - name: http
      protocol: TCP
      port: 300
      targetPort: 3001
  type: LoadBalancer